### ISSUE TITLE
Wiki по данной библиотеке

### ISSUE THREAD

**Issue by anomal3** [Agasper/Networking#1]
Приветствую ещё раз Александр.
А почему нету Wiki по данной библиотеке?

Она на столько простой оказалась, я просто в шоке. Изучал tcp протокол и блин думал, почему всё так сложно? а тут в 2 строчки подняли сервер, ещё в 2 строчки подключили клиента.
Капец как всё просто.
![37](https://user-images.githubusercontent.com/12729713/80969788-34df2a80-8e2b-11ea-8686-f8639c96f570.png)

Может я дурак и не правильно подключаюсь?
Но всё ок.
 
```csharp  
//Запускаю так сервер
var server = new SolarGames.Networking.TcpServer("127.0.0.1", 2222);
server.Listen(0);

//А так подключаю  клиента
SolarGames.Networking.TcpClient client = new SolarGames.Networking.TcpClient();
            client.Connect("127.0.0.1", 2222);
            if (client.Connected) MessageBox.Show("Client " + client.Connected);
```

Или я чего то не правильно делаю?

**Comment by Agasper** [comment]
Все верно, библиотека писалась давно под какой-то из своих проектов. Вики нет, потому что не планировалась поддержка. Это скорее пример использования сокетов. Внутри там тоже все довольно просто.

**Comment by Agasper** [comment]
Так же код написан под старый Framework, и требует доработки напильником, т.к. он не оптимизирован

**Comment by anomal3** [comment]
Блин я мучался с изучением протоколов датаграммы мать их, нифига не понятно, из примеров смог сам сделать сервер который падал, и не хотел хранить клиентов.


> Так же код написан под старый Framework, и требует доработки напильником, т.к. он не оптимизирован

Блин так тут даже предусмотрена блокировка потока при отключении
```csharp
lock (connections)
            {
                for (int i = 0; i < connections.Count; i++)
                {
                    connections[i].Close();
                }
                connections.Clear();
            }
```

Я о таком даже не мечтал.
Но Wiki очень хочется. Не всё могу понять, что за что отвечает. Не профи я ещё

**Comment by Agasper** [comment]
Современный Framework перешел на Concurrent коллекции и асинхронность, этот код морально и практически устарел на много лет, и подходит только для примера работы.

**Comment by anomal3** [comment]
> Современный Framework перешел на Concurrent коллекции и асинхронность, этот код морально и практически устарел на много лет, и подходит только для примера работы.

Не будет wiki я понял.
Потокобезопасные коллекции для моего знания пока не доступны.

**Comment by Agasper** [comment]
Новая сетевая библиотека теперь находится по адресу:
https://github.com/Agasper/Warden.NetRpc

Wiki в процессе
Этот репозитарий будет закрыт
